apiVersion: v1
kind: Service
metadata:
  name: alertmanager-lb
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
    - port: 9093
      targetPort: 9093
      protocol: TCP
      name: web
  selector:
    app.kubernetes.io/name: alertmanager
