apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql
                  image: mysql:latest
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mysql-secret
                                key: DB_PASSWORD
                      - name: MYSQL_DATABASE
                        valueFrom:
                            secretKeyRef:
                                name: mysql-secret
                                key: DB_NAME
                  ports:
                      - containerPort: 3306
                  volumeMounts:
                      - name: mysql-persistent-storage
                        mountPath: /var/lib/mysql
                      - name: mysql-init-script
                        mountPath: /docker-entrypoint-initdb.d
            volumes:
                - name: mysql-persistent-storage
                  emptyDir: {} # Replace with PVC for real persistence
                - name: mysql-init-script
                  configMap:
                      name: mysql-init-script
