apiVersion: v1
kind: Service
metadata:
    name: php-service
spec:
    selector:
        app: webapp
    ports:
        - port: 80
          targetPort: 80
    type: NodePort
    ports:
        - port: 80
          targetPort: 80
