apiVersion: apps/v1
kind: Deployment
metadata:
    name: webapp
spec:
    replicas: 2
    selector:
        matchLabels:
            app: webapp
    template:
        metadata:
            labels:
                app: webapp
        spec:
            containers:
                - name: webapp
                  image: gcr.io/cnas-assignment/webapp:latest
                  ports:
                      - containerPort: 80
                  env:
                      - name: DB_HOST
                        valueFrom:
                            secretKeyRef:
                                name: mysql-secret
                                key: DB_HOST
                      - name: DB_USER
                        valueFrom:
                            secretKeyRef:
                                name: mysql-secret
                                key: DB_USER
                      - name: DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mysql-secret
                                key: DB_PASSWORD
                      - name: DB_NAME
                        valueFrom:
                            secretKeyRef:
                                name: mysql-secret
                                key: DB_NAME
                      - name: DB_PORT
                        valueFrom:
                            secretKeyRef:
                                name: mysql-secret
                                key: DB_PORT

                  volumeMounts:                                   # ← ADD THIS BLOCK
                      - name: php-config
                        mountPath: /usr/local/etc/php/php.ini
                        subPath: php.ini

            volumes:                                             # ← ADD THIS BLOCK UNDER `spec`
                - name: php-config
                  configMap:
                      name: php-config
